# Generated by Django 5.2.3 on 2025-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='指導日')),
                ('student_name', models.CharField(max_length=100, verbose_name='生徒名')),
                ('subject', models.CharField(max_length=50, verbose_name='教科')),
                ('duration', models.IntegerField(help_text='分単位で入力', verbose_name='指導時間（分）')),
                ('content', models.TextField(verbose_name='指導内容')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='宿題')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録作成日')),
            ],
        ),
    ]
